### ISSUE TITLE
Currency input in Bulgaria (bg-BG) refuse to accept digit 4 as legal input (v.1.22.6)

### ISSUE THREAD

**Issue by OrenLX** [dm4t2/vue-currency-input#296]
### Vue Currency Input version

1.22.6

### Vue version

2.6.12

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction link

https://codesandbox.io/s/orenlx-bulgaria-bug-5mclo

### Describe your issue

Hello, 

We're using version 1.22.6 here. due complexity of code we're avoiding at the moment from upgrading the package (although it's on the roadmap).
Recently we got a complaint from a customer living in Bulgaria - seems like when the currency input works on "bg-BG" mode, and only with it (US, or any other European country seems to work well), the input refuses to accept the digit 4 into it.

If you type 0.4, it will result in 0. 
If you type 1.4 it will result in 1.
if you type 1.456, it will result in 1.56.

We use the directives method, and you can check out the issue in the attached code sandbox link.

It's a bit hard to track down in source code what might be the reason, but I suspect the formatting configuration is a bit off with Bulgaria (if any use in custom formats). Would love to hear any ideas on how to resolve the issue at the legacy version.

Thank you!

**Comment by dm4t2** [comment]
Thanks for reporting :+1: 
I have looked into this issue, which is caused by the fact that the Bulgarian locale has no grouping separator in the currency formatting. This also affects v2.

Please note, that v1 is no longer maintained and this will only be fixed for v2.

**Comment by dm4t2** [comment]
Fixed in [v2.1.3](https://github.com/dm4t2/vue-currency-input/releases/tag/2.1.3) 🎉 
You can test it on the [playground](https://dm4t2.github.io/vue-currency-input/playground.html): locale `bg-BG` and currency `BGN` have been added.

**Comment by n4rq5** [comment]
@dm4t2 Looks like this issue is still here as a regression. At least on the playground it looks to behave unexpectedly.

![image](https://user-images.githubusercontent.com/2842629/204813349-1bbd3975-3294-43c5-ad12-042d602134a4.png)

**Comment by dm4t2** [comment]
@n4rq5 Thanks for the hint! This issue is caused when using `useGrouping: true` together with locales that use grouping by default (like "bg").

**Comment by dm4t2** [comment]
Finally fixed in [v3.0.3](https://github.com/dm4t2/vue-currency-input/releases/tag/3.0.3) 🎉
