### ISSUE TITLE
Combination of currency=null, hideGroupingSymbol=false and locale 'de-DE' not working properly

### ISSUE THREAD

**Issue by trpimir-vucak-enermarket** [dm4t2/vue-currency-input#40]
Hello,

in the combination
`{
    locale: 'de-DE',
    currency: null,
   hideGroupingSymbol: false
}`
the input doesn't accept more than 4 digits:
![hide](https://user-images.githubusercontent.com/52970448/67967302-ac769780-fc05-11e9-9bdd-4ac094a94146.gif)

If i set hideGroupingSymbol to _**true**_  OR set a currency it works fine:
![show](https://user-images.githubusercontent.com/52970448/67967312-af718800-fc05-11e9-8111-af4a62a2ebf0.gif)

There seems to be multiple combinations where its working/not working.
Please help :)

**Comment by dm4t2** [comment]
Hi, thanks for reporting. I'll take a look at it.

**Comment by dm4t2** [comment]
I just fixed this issue in release 1.11.2.

**Comment by trpimir-vucak-enermarket** [comment]
Thank you for your quick response!

**Comment by trpimir-vucak-enermarket** [comment]
Unfortunately it didn't fix it. Now i can enter more than 4 digits but as soon as i leave the input, the digits after the "." are being cut off.
E.g.: Enter **12.322** , leave the input: **12**

**Comment by dm4t2** [comment]
It's a little tricky 😉

**Comment by dm4t2** [comment]
It should work now in release 1.11.3 🎉
